## 5.Predictive Modeling

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [2]:
df=pd.read_csv('C:/Users/ADMIN/Downloads/Match_details.csv')

In [3]:
df.head()

id   season        city        date match_type player_of_match  \
0  335982  2007/08   Bangalore  2008-04-18     League     BB McCullum   
1  335983  2007/08  Chandigarh  2008-04-19     League      MEK Hussey   
2  335984  2007/08       Delhi  2008-04-19     League     MF Maharoof   
3  335985  2007/08      Mumbai  2008-04-20     League      MV Boucher   
4  335986  2007/08     Kolkata  2008-04-20     League       DJ Hussey   

                                        venue                        team1  \
0                       M Chinnaswamy Stadium  Royal Challengers Bangalore   
1  Punjab Cricket Association Stadium, Mohali                 Punjab Kings   
2                            Feroz Shah Kotla               Delhi Capitals   
3                            Wankhede Stadium               Mumbai Indians   
4                                Eden Gardens        Kolkata Knight Riders   

                         team2                  toss_winner toss_decision  \
0        Kolkata Knight Riders  Royal Challengers Bangalore         field   
1          Chennai Super Kings          Chennai Super Kings           bat   
2             Rajasthan Royals             Rajasthan Royals           bat   
3  Royal Challengers Bangalore               Mumbai Indians           bat   
4          Sunrisers Hyderabad          Sunrisers Hyderabad           bat   

                        winner   result  result_margin  target_runs  \
0        Kolkata Knight Riders     runs          140.0        223.0   
1          Chennai Super Kings     runs           33.0        241.0   
2               Delhi Capitals  wickets            9.0        130.0   
3  Royal Challengers Bangalore  wickets            5.0        166.0   
4        Kolkata Knight Riders  wickets            5.0        111.0   

   target_overs super_over method    umpire1         umpire2  
0          20.0          N    NaN  Asad Rauf     RE Koertzen  
1          20.0          N    NaN  MR Benson      SL Shastri  
2          20.0          N    NaN  Aleem Dar  GA Pratapkumar  
3          20.0          N    NaN   SJ Davis       DJ Harper  
4          20.0          N    NaN  BF Bowden     K Hariharan

In [4]:
df.isnull().sum()

id                    0
season                0
city                  0
date                  0
match_type            0
player_of_match       0
venue                 0
team1                 0
team2                 0
toss_winner           0
toss_decision         0
winner                0
result                0
result_margin         0
target_runs           0
target_overs          0
super_over            0
method             1074
umpire1               0
umpire2               0
dtype: int64

In [5]:
df['method'].fillna('None', inplace=True)

In [6]:
df.dtypes

id                   int64
season              object
city                object
date                object
match_type          object
player_of_match     object
venue               object
team1               object
team2               object
toss_winner         object
toss_decision       object
winner              object
result              object
result_margin      float64
target_runs        float64
target_overs       float64
super_over          object
method              object
umpire1             object
umpire2             object
dtype: object

In [7]:
df['date']=pd.to_datetime(df['date'])

In [8]:
matches = df[['toss_winner', 'toss_decision', 'venue', 'team1', 'team2', 'winner']]

In [9]:
matches=matches[matches['winner']!='No Winner']

In [10]:
from sklearn.preprocessing import LabelEncoder

In [11]:
label_enc = LabelEncoder()
matches['toss_winner'] = label_enc.fit_transform(matches['toss_winner'])
matches['winner'] = label_enc.transform(matches['winner'])  # Target variable
matches['team1'] = label_enc.fit_transform(matches['team1'])
matches['team2'] = label_enc.transform(matches['team2'])
matches['venue'] = label_enc.fit_transform(matches['venue'])
matches['toss_decision'] = matches['toss_decision'].map({'bat': 0, 'field': 1}) 

In [12]:
# Define features (X) and target variable (y)
X = matches[['toss_winner', 'toss_decision', 'venue', 'team1', 'team2']]
y = matches['winner']

# Split into training (80%) and testing (20%) sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [13]:
# Train Logistic Regression model
log_model = LogisticRegression()
log_model.fit(X_train, y_train)

# Predict on test data
y_pred_log = log_model.predict(X_test)

C:\Users\ADMIN\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [14]:
# Train Random Forest model
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)

# Predict on test data
y_pred_rf = rf_model.predict(X_test)

In [15]:
# train Decision Tree Model
dt_model=DecisionTreeClassifier()
dt_model.fit(X_train,y_train)

# Predict on test data
y_pred_dt=dt_model.predict(X_test)

In [16]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, roc_auc_score

In [17]:
print("Logistic Regression Accuracy:", accuracy_score(y_test, y_pred_log))
print("Random Forest Accuracy:", accuracy_score(y_test, y_pred_rf))
print("Decisition Tree Accuracy:", accuracy_score(y_test, y_pred_dt))

Logistic Regression Accuracy: 0.22018348623853212
Random Forest Accuracy: 0.5045871559633027
Decisition Tree Accuracy: 0.4954128440366973


In [18]:
print("Confusion Matrix (Logistic Regression):\n", confusion_matrix(y_test, y_pred_log))
print("Confusion Matrix (Random Forest):\n", confusion_matrix(y_test, y_pred_rf))
print("Confusion Matrix (Desicion Tree):\n", confusion_matrix(y_test, y_pred_dt))

Confusion Matrix (Logistic Regression):
 [[11 15  0  0  0  2  0  7  0  0  0  0  1  1]
 [ 5  6  0  0  0  3  0  5  0  0  1  0  0  0]
 [ 1  3  0  0  0  0  0  1  0  0  0  0  0  0]
 [ 2  2  0  0  0  2  0  1  0  1  1  0  0  0]
 [ 1  1  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 1  4  0  0  0  2  0  2  0  3  0  0  6  5]
 [ 0  1  0  0  0  0  0  0  0  0  0  0  1  1]
 [ 5  2  0  0  0  1  0  8  0  0  1  0  5  4]
 [ 0  1  0  0  0  0  0  0  0  0  1  0  1  0]
 [ 1  2  0  0  0  2  0  8  0  0  0  0  1  6]
 [ 1  1  0  0  0  0  0 11  0  0  2  0  4  6]
 [ 0  0  0  0  0  1  0  1  0  0  0  0  1  1]
 [ 0  2  0  0  0  1  0  5  0  0  1  0 10  9]
 [ 0  0  0  0  0  1  0  0  0  0  0  0  3  9]]
Confusion Matrix (Random Forest):
 [[24  2  0  1  0  0  1  0  0  3  0  0  4  2]
 [ 1  6  1  0  0  0  0  2  1  3  2  0  0  4]
 [ 0  0  3  0  0  0  0  1  0  0  0  0  1  0]
 [ 1  2  0  3  0  1  0  0  0  0  2  0  0  0]
 [ 0  0  0  0  0  2  0  0  0  0  0  0  0  0]
 [ 2  0  0  0  0 12  0  4  0  0  0  0  1  4]
 [ 0  0  0  0  0  1  1 

In [20]:
from sklearn.metrics import roc_auc_score
# Compute ROC-AUC for multi-class classification
print("ROC-AUC (Logistic Regression):", roc_auc_score(y_test, log_model.predict_proba(X_test), multi_class="ovr"))
print("ROC-AUC (Random Forest):", roc_auc_score(y_test, rf_model.predict_proba(X_test), multi_class="ovr"))
print("ROC-AUC (Desicion Tree):", roc_auc_score(y_test, dt_model.predict_proba(X_test),multi_class='ovr'))

ROC-AUC (Logistic Regression): 0.6702224180500115
ROC-AUC (Random Forest): 0.935521273157382
ROC-AUC (Desicion Tree): 0.7254949599608719
